import type {Episode} from "./mentions";

// Episodes
export const episodes: Episode[] = [
  // 2024 Episodes
  {
    id: 21,
    title: "As previsões que ninguém pediu sobre A.I. e Produto em 2024",
    date: "2024-01-10",
    description: "Discussão sobre previsões para inteligência artificial e produto em 2024.",
    youtubeLink: "https://www.youtube.com/watch?v=tT8ytrU2Dtw",
    spotifyLink: "https://open.spotify.com/episode/234RzKezAqJCQWscOt6itu",
  },
  {
    id: 22,
    title: "Como a galera tá usando o ChatGPT no dia a dia?",
    date: "2024-01-17",
    description: "Discussão sobre os usos práticos do ChatGPT no cotidiano das pessoas.",
    youtubeLink: "https://www.youtube.com/watch?v=fWEQ6sWa-1k",
    spotifyLink: "https://open.spotify.com/episode/47ew2fmvqotNS7wEctCXo1",
  },
  {
    id: 23,
    title: "PMs precisam postar na Linkedisney pra ter sucesso?",
    date: "2024-01-24",
    description: "Discussão sobre a presença de Product Managers no LinkedIn e se isso é necessário para o sucesso na carreira.",
    youtubeLink: "https://www.youtube.com/watch?v=VRKREVXlr5k",
    spotifyLink: "https://open.spotify.com/episode/79xhRjhraaoWfgycFFaGfg",
  },
  {
    id: 24,
    title: "PMs e Zona de conforto, Palworld e esportes na Netflix",
    date: "2024-01-31",
    description: "Discussão sobre Product Managers e zona de conforto, o fenômeno Palworld e a entrada da Netflix no esporte.",
    youtubeLink: "https://www.youtube.com/watch?v=qGFGrS1zPMs",
    spotifyLink: "https://open.spotify.com/episode/5wfNRHd9Uk96QEGGBQlMFV",
  },
  {
    id: 25,
    title: 'Apple Vision Pro: será que chegou a "the next big thing?"',
    date: "2024-02-07",
    description: "Discussão sobre o lançamento do Apple Vision Pro e se ele representa a próxima grande revolução tecnológica.",
    youtubeLink: "https://www.youtube.com/watch?v=9oudl3f6WCo",
    spotifyLink: "https://open.spotify.com/episode/7DaNBfb9HNLH7IqUYB7QWt",
  },
  {
    id: 27,
    title: "Ideia boa é ideia na rua; um podcast feito por AI",
    date: "2024-02-28",
    description: "Discussão sobre a importância de colocar ideias em prática e a criação de podcasts com inteligência artificial.",
    youtubeLink: "https://www.youtube.com/watch?v=SJ-JTwdBtQk",
    spotifyLink: "https://open.spotify.com/episode/1TMI0R8dZvDnyEUnQsyWI2",
  },
  {
    id: 28,
    title: "A métrica de sucesso para Product Leaders e já imaginou a internet sem ads?",
    date: "2024-03-07",
    description: "Discussão sobre métricas de sucesso para líderes de produto e uma reflexão sobre uma internet sem anúncios.",
    youtubeLink: "https://www.youtube.com/watch?v=ax0HXsyi9xY",
    spotifyLink: "https://open.spotify.com/episode/5roegYPH0UPG19ba6dwEJ9",
  },
  {
    id: 29,
    title: "Cagan ON FIRE!",
    date: "2024-03-12",
    description: "Discussão sobre as ideias de Marty Cagan e sua aplicação no mundo de produto.",
    youtubeLink: "https://www.youtube.com/watch?v=rocthk-PcHY",
    spotifyLink: "https://open.spotify.com/episode/5FgAMd2QyxP9ZTdTdxDNHI",
  },
  {
    id: 30,
    title: "A.I. e Futebol dá jogo? Como se tornar um PM mais técnico",
    date: "2024-04-05",
    description: "Discussão sobre inteligência artificial no futebol e como se tornar um product manager mais técnico.",
    youtubeLink: "https://www.youtube.com/watch?v=suWAYoNoCj8",
    spotifyLink: "https://open.spotify.com/episode/6rKgVb9CC16H7MmmIXey2Q",
  },
  {
    id: 31,
    title: "Ninguém liga para o seu processo",
    date: "2024-04-09",
    description: "Discussão sobre processos e como eles impactam (ou não) a percepção do usuário final.",
    youtubeLink: "https://www.youtube.com/watch?v=CdtUOrwQQEI",
    spotifyLink: "https://open.spotify.com/episode/7ixhXQLSz5EYCCfUFHAiF1",
  },
  {
    id: 32,
    title: "O flop do AI Pin e a relação do Poker com Produto",
    date: "2024-04-17",
    description: "Discussão sobre o fracasso do AI Pin da Humane e a relação entre estratégias de poker e produto.",
    youtubeLink: "https://www.youtube.com/watch?v=tHoLSaJSymY",
    spotifyLink: "https://open.spotify.com/episode/41XKPLZSrzPpxISjX7cLeS",
  },
  {
    id: 33,
    title: "O direito de se desconectar e quando microgerenciamento não é ruim",
    date: "2024-04-24",
    description: "Discussão sobre o direito de se desconectar do trabalho e quando o microgerenciamento pode ser benéfico.",
    youtubeLink: "https://www.youtube.com/watch?v=1qznxnxz-hQ",
    spotifyLink: "https://open.spotify.com/episode/6D8bU4LWXJrvA2W7diDCdp",
  },
  {
    id: 34,
    title: "Comunicação em poucas palavras e como desenvolver PMs sem bullsh**agem",
    date: "2024-05-01",
    description: "Discussão sobre comunicação assertiva e desenvolvimento de product managers.",
    youtubeLink: "https://www.youtube.com/watch?v=jvWFkhjd4iA",
    spotifyLink: "https://open.spotify.com/episode/1Ug1EFJFQADgfNkvDTjuD8",
  },
  {
    id: 35,
    title: "Cultura, silos, aquisições e politicagem",
    date: "2024-05-07",
    description: "Discussão sobre cultura organizacional, silos, aquisições e politicagem no mundo de produto.",
    youtubeLink: "https://www.youtube.com/watch?v=ZPP8EXU3ygg",
    spotifyLink: "https://open.spotify.com/episode/7gL3Negla9m9imsJtBp43M",
  },
  {
    id: 36,
    title: "Os lançamentos da OpenAI e do Google",
    date: "2024-05-14",
    description: "Discussão sobre os lançamentos recentes da OpenAI e do Google.",
    youtubeLink: "https://www.youtube.com/watch?v=p7EtnWxjGhA",
    spotifyLink: "https://open.spotify.com/episode/3alwBDl2DTde1NgNul0rZo",
  },
  {
    id: 37,
    title: "Aprendendo sobre pensamento crítico e analítico",
    date: "2024-05-21",
    description: "Discussão sobre pensamento crítico e analítico no contexto de produto.",
    youtubeLink: "https://www.youtube.com/watch?v=jLWibqR_Fwo",
    spotifyLink: "https://open.spotify.com/episode/6pjfzGJfaiyiWq2qSJR3af",
  },
  {
    id: 38,
    title: 'E quando "falta tempo" para consumir conteúdo? Um giro de notícias no mundo de A.I.',
    date: "2024-05-28",
    description: "Discussão sobre consumo de conteúdo e um giro de notícias no mundo de inteligência artificial.",
    youtubeLink: "https://www.youtube.com/watch?v=FK2i6yDW0T0",
    spotifyLink: "https://open.spotify.com/episode/32UgeXpOOUkzevTtoocLhv",
  },
  {
    id: 39,
    title: "Opiniões fortes, convicção e hype na construção de produtos",
    date: "2024-06-04",
    description: "Discussão sobre opiniões fortes, convicção e hype no processo de construção de produtos.",
    youtubeLink: "https://www.youtube.com/watch?v=vJc49mxRvig",
    spotifyLink: "https://open.spotify.com/episode/1Nk7xxuPD3Bg9tZLjpv6pI",
  },
  {
    id: 41,
    title: "Estratégias de A.I.: integrações, modelos e custos",
    date: "2024-06-26",
    description: "Discussão sobre estratégias de inteligência artificial: integrações, modelos e custos.",
    youtubeLink: "https://www.youtube.com/watch?v=ZOLQyN6lnxM",
    spotifyLink: "https://open.spotify.com/episode/4gCPwl04SZaNS9LZf5SU0H",
  },
  {
    id: 42,
    title: "A conferência do Figma e as comunidades de design e produto",
    date: "2024-07-02",
    description: "Discussão sobre a conferência do Figma e o ecossistema das comunidades de design e produto.",
    youtubeLink: "https://www.youtube.com/watch?v=ovZbc1AosZg",
    spotifyLink: "https://open.spotify.com/episode/19BtSb18iLhIMLQov93bm5",
  },
  {
    id: 43,
    title: "O novo modelo da Meta, Vendas do Ray-Ban bombando e os desafios da Netflix com conteúdos ao vivo",
    date: "2024-07-24",
    description: "Discussão sobre o novo modelo de IA da Meta, o sucesso de vendas do Ray-Ban e os desafios da Netflix com transmissões ao vivo.",
    youtubeLink: "https://www.youtube.com/watch?v=cV_bTxTo-Xo",
    spotifyLink: "https://open.spotify.com/episode/16QS6NpX686gaIg5aLBkZ0",
  },
  {
    id: 45,
    title: "Claude no Brasil, saídas da Open AI e a Nvidia pega no flagra pirateando",
    date: "2024-08-07",
    description: "Discussão sobre Claude chegando ao Brasil, movimentações na OpenAI e controvérsia envolvendo Nvidia.",
    youtubeLink: "https://www.youtube.com/watch?v=PfQ59NhQ2xI",
    spotifyLink: "https://open.spotify.com/episode/5bsZ5Gw5Gpr2tfDGhfYKtU",
  },
  {
    id: 46,
    title: "O presente e o futuro dos produtos de AI e Existe um mundo além das squads?",
    date: "2024-08-14",
    description: "Discussão sobre o presente e futuro dos produtos de inteligência artificial e reflexões sobre estruturas organizacionais.",
    youtubeLink: "https://www.youtube.com/watch?v=kV2j9THFycM",
    spotifyLink: "https://open.spotify.com/episode/2Qw7h1EKpj7IuuxGeLo08P",
  },
  {
    id: 47,
    title: "Nossas técnicas de produtividade (sem ligação com AI)",
    date: "2024-08-21",
    description: "Discussão sobre técnicas de produtividade sem o uso de inteligência artificial.",
    youtubeLink: "https://www.youtube.com/watch?v=Uy5YsbmgKfg",
    spotifyLink: "https://open.spotify.com/episode/5hRqP2dE49YRjTZWguy4z1",
  },
  {
    id: 48,
    title: "Design Engineer - Essa moda vai pegar?",
    date: "2024-08-28",
    description: "Discussão sobre a tendência de Design Engineers e as ferramentas da semana.",
    youtubeLink: "https://www.youtube.com/watch?v=5p9TU1_BpCw",
    spotifyLink: "https://open.spotify.com/episode/35WZmYhbglxXzEc5T3kmo9",
  },
  {
    id: 49,
    title: "Redesign problemático, roadmap público e queda das ações: O caso da Sonos",
    date: "2024-09-04",
    description: "Análise do caso Sonos: redesign, roadmap público e impacto nas ações.",
    youtubeLink: "https://www.youtube.com/watch?v=w-QhACf3XoQ",
    spotifyLink: "https://open.spotify.com/episode/4lQads2MkEn0uKKzhbNmI2",
  },
  {
    id: 51,
    title: "Velocidade vs. Qualidade e as táticas de growth que [não] funcionam",
    date: "2024-09-18",
    description: "Discussão sobre o equilíbrio entre velocidade e qualidade e táticas de growth.",
    youtubeLink: "https://www.youtube.com/watch?v=794sVRaQjNQ",
    spotifyLink: "https://open.spotify.com/episode/4g91Oig6hu7yABp2abzJOm",
  },
  {
    id: 52,
    title: "Panorama do Mercado de Produto do Brasil",
    date: "2024-09-25",
    description: "Análise do panorama atual do mercado de produto no Brasil.",
    youtubeLink: "https://www.youtube.com/watch?v=-COtX2uM_Dk",
    spotifyLink: "https://open.spotify.com/episode/4cCJ0DXGSKhDjkhhx4Rw8a",
  },
  {
    id: 53,
    title: "Highlights do Product Leader Summit 2024",
    date: "2024-10-02",
    description: "Destaques e aprendizados do Product Leader Summit 2024.",
    youtubeLink: "https://www.youtube.com/watch?v=3Mw7wlIfqUc",
    spotifyLink: "https://open.spotify.com/episode/5FBI8Bsb5Wl7SWbGIPwZzd",
  },
  {
    id: 55,
    title: "Gestão de Plataformas e APIs para PMs não técnicos - um papo com Sheila Chang",
    date: "2024-10-15",
    description: "Entrevista com Sheila Chang sobre gestão de plataformas e APIs.",
    youtubeLink: "https://www.youtube.com/watch?v=PcANWhQEMWo",
    spotifyLink: "https://open.spotify.com/episode/6goU5jYZdrxcOiYChx3q2s",
  },
  {
    id: 56,
    title: "Carreira internacional, Mulheres na Liderança e Maternidade - Gisele Góes (Chime)",
    date: "2024-10-22",
    description: "Entrevista com Gisele Góes sobre carreira internacional e liderança feminina.",
    youtubeLink: "https://www.youtube.com/watch?v=Hk7_LnFe6hY",
    spotifyLink: "https://open.spotify.com/episode/58SiJwaFDJJMjI7HXPGBiu",
  },
  {
    id: 57,
    title: "Reflexões sobre fazer o básico bem feito",
    date: "2024-10-30",
    description: "Discussão sobre a importância de executar bem o básico.",
    youtubeLink: "https://www.youtube.com/watch?v=PkJf-kVxuuk",
    spotifyLink: "https://open.spotify.com/episode/6Q5UbV5s1otRNJQcF1tHE7",
  },
  {
    id: 58,
    title: "Como foi o Lenny & Friends Summit? Com Fernanda Faria-Product Director @ ABInBev",
    date: "2024-11-06",
    description: "Discussão sobre o Lenny & Friends Summit com Fernanda Faria.",
    youtubeLink: "https://www.youtube.com/watch?v=5z4cqkC9COA",
    spotifyLink: "https://open.spotify.com/episode/3QvuUuzciPRDuTz6qbY58m",
  },
  {
    id: 59,
    title: "O que chefões da OpenAI, Anthropic e Perplexity pensam sobre AI como produto",
    date: "2024-11-12",
    description: "Discussão sobre visões de AI como produto por líderes da OpenAI, Anthropic e Perplexity.",
    youtubeLink: "https://www.youtube.com/watch?v=hp_L2ASyrqg",
    spotifyLink: "https://open.spotify.com/episode/5UI0e16XrpxZF16TXymrGK",
  },
  {
    id: 60,
    title: "Quem cria a visão de Produto?",
    date: "2024-11-19",
    description: "Discussão sobre quem é responsável por criar a visão de produto.",
    youtubeLink: "https://www.youtube.com/watch?v=RWLPKIsZrxE",
    spotifyLink: "https://open.spotify.com/episode/6RX0BIHffDX0NAlAgSK0ia",
  },
  {
    id: 61,
    title: "Como saber e quais os sinais se um produto vai dar bom ou não?",
    date: "2024-11-26",
    description: "Discussão sobre sinais de sucesso e fracasso de produtos.",
    youtubeLink: "https://www.youtube.com/watch?v=A6JYg0vm7Hw",
    spotifyLink: "https://open.spotify.com/episode/1OQ89dewSwsUdxLtN8yHHz",
  },
  {
    id: 62,
    title: "Comunicação executiva & Como dar melhores feedbacks de design?",
    date: "2024-12-03",
    description: "Dicas sobre comunicação executiva e feedbacks de design.",
    youtubeLink: "https://www.youtube.com/watch?v=Dv8PE958MJ4",
    spotifyLink: "https://open.spotify.com/episode/3cUfsZm4BG4Bqf1uLBkiny",
  },
  {
    id: 63,
    title: "Chegou ao fim a camada de GPMs?",
    date: "2024-12-10",
    description: "Discussão sobre o futuro da função de GPM.",
    youtubeLink: "https://www.youtube.com/watch?v=dDHf0Ku0OSw",
    spotifyLink: "https://open.spotify.com/episode/4GZS7Mohm2fZx5BDHN5RPJ",
  },
  {
    id: 64,
    title: "Retrospectiva Produteira 2024: Foi um péssimo ano para a área de produto?",
    date: "2024-12-17",
    description: "Retrospectiva do ano de 2024 para a área de produto.",
    youtubeLink: "https://www.youtube.com/watch?v=dzNgj2BeBPw",
    spotifyLink: "https://open.spotify.com/episode/5k5Dxrn99FZQmj2yLB4vWq",
  },
  // 2025 Episodes
  {
    id: 65,
    title: "As previsões que ninguém pediu sobre Produto, AI e mercado tech em 2025",
    date: "2025-01-08",
    description: "Previsões sobre produto, IA e o mercado tech para 2025.",
    youtubeLink: "https://www.youtube.com/watch?v=MkY8Fk2Zen0",
    spotifyLink: "https://open.spotify.com/episode/20oyevb7btvvNiS7B5YUO2",
  },
  {
    id: 66,
    title: "Dicas para ter conversas difíceis e Como fazer protótipos com AI",
    date: "2025-01-15",
    description: "Discussões sobre conversas difíceis e prototipagem com IA.",
    youtubeLink: "https://www.youtube.com/watch?v=EhubWDEdE9k",
    spotifyLink: "https://open.spotify.com/episode/4pjMq5qTNcR1zEt2NQeNdy",
  },
  {
    id: 67,
    title: "A importância dos 'selos' na carreira de produtos e a hora dos generalistas",
    date: "2025-01-22",
    description: "Reflexões sobre carreira de produtos e o papel dos generalistas.",
    youtubeLink: "https://www.youtube.com/watch?v=n5tp6fN1V0k",
    spotifyLink: "https://open.spotify.com/episode/1a6g32uZuzCP63QfykXR6E",
  },
  {
    id: 68,
    title: "DeepSeek para Leigos: o modelo chinês que chegou para causar!",
    date: "2025-01-29",
    description: "Análise do DeepSeek e seu impacto no mercado de IA.",
    youtubeLink: "https://www.youtube.com/watch?v=uNwjPQLjKMI",
    spotifyLink: "https://open.spotify.com/episode/7dLcZZ3dLyF8lAWJwDPvbU",
  },
  {
    id: 69,
    title: "Criando comunidades, matando features e priorizando no-code, com Beatriz Kinguti, CPO da LITI saúde",
    date: "2025-02-05",
    description: "Entrevista com Beatriz Kinguti sobre comunidades e no-code.",
    youtubeLink: "https://www.youtube.com/watch?v=_CpDJp1-EMU",
    spotifyLink: "https://open.spotify.com/episode/3G7bbuIKLysDTKx6o76EKi",
  },
  {
    id: 70,
    title: "Nossas experiências construindo apps com AI",
    date: "2025-02-12",
    description: "Experiências práticas construindo aplicativos com IA.",
    youtubeLink: "https://www.youtube.com/watch?v=DQvBEbF4fUs",
    spotifyLink: "https://open.spotify.com/episode/6x07AgGwIYiejhVvwaf1WH",
  },
  {
    id: 71,
    title: "O Handbook do Duolingo vai ser o novo 'modelo Spotify'?",
    date: "2025-02-19",
    description: "Análise do handbook do Duolingo e seu impacto na indústria.",
    youtubeLink: "https://www.youtube.com/watch?v=gm2dPWh8wv0",
    spotifyLink: "https://open.spotify.com/episode/0iPDQ9YYg4iqgyAx38nSGZ",
  },
  {
    id: 72,
    title: "Seu roadmap vai mudar, e tá tudo bem.",
    date: "2025-02-26",
    description: "Discussão sobre flexibilidade no planejamento de produto.",
    youtubeLink: "",
    spotifyLink: "https://open.spotify.com/episode/6AFZ4fhBACtJs8FsAfSxfp",
  },
  {
    id: 73,
    title: "AI Mudando o roadmap da Apple e Figma e Como manter a energia de produto no alto?",
    date: "2025-03-12",
    description: "Impacto da IA nos roadmaps de grandes empresas.",
    youtubeLink: "https://www.youtube.com/watch?v=2IGxSlxFd34",
    spotifyLink: "https://open.spotify.com/episode/4572iicjlZkRVC5Ygryi7G",
  },
  {
    id: 74,
    title: "Métricas, pra que te quero?!",
    date: "2025-03-19",
    description: "Discussão sobre o uso de métricas em produto.",
    youtubeLink: "https://www.youtube.com/watch?v=xYACIBWDbCI",
    spotifyLink: "https://open.spotify.com/episode/3O5jA6jLCtkOQAFJaYEoEI",
  },
  {
    id: 75,
    title: "Contratação de PMs - o que não pode faltar?",
    date: "2025-03-26",
    description: "Dicas para contratação de Product Managers.",
    youtubeLink: "https://www.youtube.com/watch?v=8r5aafUHVj0",
    spotifyLink: "https://open.spotify.com/episode/2kn9gI9hWszQBQTRTYc4g4",
  },
  {
    id: 76,
    title: "O que muda em produto com o novo modelo da OpenAI",
    date: "2025-04-02",
    description: "Impacto do novo modelo da OpenAI em produtos.",
    youtubeLink: "https://www.youtube.com/watch?v=uPTmRRREKC8",
    spotifyLink: "https://open.spotify.com/episode/1x3TQ7caYv3ZYRhtMk3xD7",
  },
  {
    id: 77,
    title: "O plano do Shopify para forçar toda a empresa a usar AI",
    date: "2025-04-08",
    description: "Análise da estratégia de IA do Shopify.",
    youtubeLink: "https://www.youtube.com/watch?v=vfTnOV4vcwo",
    spotifyLink: "https://open.spotify.com/episode/7HZTXIdcTZr5inDRjep0Fs",
  },
  {
    id: 78,
    title: "Porque você deveria revisar sua agenda",
    date: "2025-04-16",
    description: "Reflexões sobre gestão de tempo e agenda.",
    youtubeLink: "https://www.youtube.com/watch?v=vRHnna2MEjc",
    spotifyLink: "https://open.spotify.com/episode/2h1E39I6CHzmiBq6ZYBd6U",
  },
  {
    id: 79,
    title: "Mitos da Liderança de Produtos",
    date: "2025-04-22",
    description: "Desmistificando crenças sobre liderança de produto.",
    youtubeLink: "https://www.youtube.com/watch?v=wrojLos80BE",
    spotifyLink: "https://open.spotify.com/episode/0C6CakD5ec1e4iyzsSL6Cr",
  },
  {
    id: 80,
    title: "Ray-Ban, anúncios e AI: os planos do Zuck para a Meta",
    date: "2025-05-07",
    description: "Análise dos planos da Meta para IA e wearables.",
    youtubeLink: "https://www.youtube.com/watch?v=46Q_Z7ZbqDo",
    spotifyLink: "https://open.spotify.com/episode/3GuZK03dHzNuNc1t04zJD4",
  },
  {
    id: 81,
    title: "Síndrome do Impostor na Liderança de Produtos",
    date: "2025-05-15",
    description: "Discussão sobre síndrome do impostor em líderes de produto.",
    youtubeLink: "https://www.youtube.com/watch?v=9dB2z3aHq9Y",
    spotifyLink: "https://open.spotify.com/episode/6GuLV5H8CArUcsnPGOluNM",
  },
  {
    id: 82,
    title: "SEMANA INSANA EM AI: Lançamentos da Anthropic, Google IO, Microsoft Build e OpenAI",
    date: "2025-05-28",
    description: "Cobertura dos principais lançamentos de IA.",
    youtubeLink: "https://www.youtube.com/watch?v=QSPXXi_WPDA",
    spotifyLink: "https://open.spotify.com/episode/4cGRM1xxaOcJ87kQTvaaeX",
  },
  {
    id: 83,
    title: "Como estamos usando IA no dia a dia? Com Éfrem Filho, Principal PM @ Pipefy",
    date: "2025-06-05",
    description: "Entrevista sobre uso prático de IA no dia a dia.",
    youtubeLink: "https://www.youtube.com/watch?v=sGIrHmJi4c0",
    spotifyLink: "https://open.spotify.com/episode/4R0K4SVBF6WjJ0UMRyDRxD",
  },
  {
    id: 84,
    title: "Redesign do iOS e os lançamentos da WWDC",
    date: "2025-06-10",
    description: "Cobertura da WWDC e novo design do iOS.",
    youtubeLink: "https://www.youtube.com/watch?v=1k8K4zvpFso",
    spotifyLink: "https://open.spotify.com/episode/37LaxmXtg62xPKUa9eSWOa",
  },
  {
    id: 85,
    title: "Como formar times que sabem levar porrada",
    date: "2025-06-18",
    description: "Discussão sobre resiliência em times de produto.",
    youtubeLink: "https://www.youtube.com/watch?v=K3NQpGUMPbo",
    spotifyLink: "https://open.spotify.com/episode/5Uzy6LOivDMZGpKNSdUX4x",
  },
  {
    id: 86,
    title: "Como a AI está reescrevendo as regras de produto e distribuição",
    date: "2025-07-01",
    description: "Impacto da IA nas regras de produto e distribuição.",
    youtubeLink: "https://www.youtube.com/watch?v=JxYOX1poJfQ",
    spotifyLink: "https://open.spotify.com/episode/1krH7zwtFxEsh0HqCfDEi4",
  },
  {
    id: 87,
    title: "O guia prático para adoção de IA na sua empresa",
    date: "2025-07-10",
    description: "Guia prático para implementar IA em empresas.",
    youtubeLink: "https://www.youtube.com/watch?v=BRQMzR7K5ls",
    spotifyLink: "https://open.spotify.com/episode/6e6GF8dzSotj40q5c0TkVb",
  },
  {
    id: 88,
    title: "Quão longe dá pra ir com AI sem um dev?",
    date: "2025-07-23",
    description: "Explorando limites do no-code com IA.",
    youtubeLink: "https://www.youtube.com/watch?v=EjseRRXBSn8",
    spotifyLink: "https://open.spotify.com/episode/69WosZB4FjJFXqCZjgDnbR",
  },
  {
    id: 89,
    title: "Tomando decisões com AI",
    date: "2025-07-30",
    description: "Como usar IA para tomada de decisões.",
    youtubeLink: "https://www.youtube.com/watch?v=zo1NvcK6JjQ",
    spotifyLink: "https://open.spotify.com/episode/6hWIC5iRTXBNarnxPMEUJi",
  },
  {
    id: 90,
    title: "ChatGPT-5: Flopou ou Revolucionou?",
    date: "2025-08-13",
    description: "Análise do ChatGPT-5 e seu impacto.",
    youtubeLink: "https://www.youtube.com/watch?v=TOz17MFL2cY",
    spotifyLink: "https://open.spotify.com/episode/66zekniqrZoG7p5wvKesg2",
  },
  {
    id: 91,
    title: "Entre tapas e beijos: a relação entre produto e engenharia",
    date: "2025-08-22",
    description: "Dinâmica entre times de produto e engenharia.",
    youtubeLink: "https://www.youtube.com/watch?v=R5pcMqKC1oo",
    spotifyLink: "https://open.spotify.com/episode/64rLQMnlbFDreawZ6w2hhx",
  },
  {
    id: 92,
    title: "O que está por trás da 'exigência' de IA nas empresas?",
    date: "2025-08-27",
    description: "Reflexões sobre a pressão por IA nas empresas.",
    youtubeLink: "https://www.youtube.com/watch?v=tQRCrTMQvXc",
    spotifyLink: "https://open.spotify.com/episode/2vAVcn23NwYLZTK66xygWS",
  },
  {
    id: 93,
    title: "Reorgs na Prática: Erros, Aprendizados e Trade-offs",
    date: "2025-09-04",
    description: "Discussão sobre reorganizações empresariais.",
    youtubeLink: "https://www.youtube.com/watch?v=vNoH1U5b_IU",
    spotifyLink: "https://open.spotify.com/episode/791OHS8VBSpSH6CgooYrw1",
  },
  {
    id: 94,
    title: "Os novos iPhones: A Apple perdeu a magia?",
    date: "2025-09-10",
    description: "Análise dos novos iPhones da Apple.",
  },
  {
    id: 95,
    title: "Meta Display: o novo iPhone?",
    date: "2025-09-22",
    description: "Análise do Meta Display e seu potencial.",
    youtubeLink: "https://www.youtube.com/watch?v=g3Y2KXfmAe0",
    spotifyLink: "https://open.spotify.com/episode/4wtO2V7ukLCY2sY0nMl60l",
  },
  {
    id: 96,
    title: "Uma semana insana de lançamentos em IA",
    date: "2025-10-01",
    description: "Cobertura de lançamentos de IA.",
    youtubeLink: "https://www.youtube.com/watch?v=3aG0314I7Z0",
    spotifyLink: "https://open.spotify.com/episode/52H1og58VbJls4jFjaoxek",
  },
  {
    id: 97,
    title: "Panorama de Produto 2025: salários e tendências",
    date: "2025-10-08",
    description: "Análise de salários e tendências em produto.",
    youtubeLink: "https://www.youtube.com/watch?v=SzQr86tX2S4",
    spotifyLink: "https://open.spotify.com/episode/38Q5Gdwza192sC7jOhx6VF",
  },
  {
    id: 98,
    title: "Como foi o Product Leader Summit 2025?",
    date: "2025-11-06",
    description: "Cobertura do Product Leader Summit 2025.",
    youtubeLink: "https://www.youtube.com/watch?v=ZOVFWGfKaTE",
    spotifyLink: "https://open.spotify.com/episode/6frGgZsE1oEwj7xildcunE",
  },
  {
    id: 99,
    title: "IA é uma bolha? O que isso muda na sua vida",
    date: "2025-11-21",
    description: "Discussão sobre a sustentabilidade da IA.",
    youtubeLink: "https://www.youtube.com/watch?v=aBnx15YhSKw",
    spotifyLink: "https://open.spotify.com/episode/6LVL69XcSrPe6aTYdWzHW2",
  },
  {
    id: 100,
    title: "Papo na Arena 100! Retrospectiva Produteira e Melhores do Ano",
    date: "2025-12-10",
    description: "Episódio 100 com retrospectiva e melhores momentos do ano.",
    youtubeLink: "https://www.youtube.com/watch?v=g9DSu1OR0DY",
    spotifyLink: "https://open.spotify.com/episode/1tRctNfRWoinK92au6wTDV",
  },
  // 2026 Episodes
  {
    id: 101,
    title: "As previsões 2026 que ninguém pediu sobre Produto, AI e mercado tech",
    date: "2026-01-14",
    description: "Previsões ousadas sobre produto, IA e o mercado tech para 2026.",
    youtubeLink: "https://www.youtube.com/watch?v=ncQTnIBwfgc",
    spotifyLink: "https://open.spotify.com/episode/1sxyo5Qw73jbm3RrocvNoJ",
  },
  {
    id: 102,
    title: "Claude Code: acabou pro ChatGPT?",
    date: "2026-01-21",
    description: "Discussão sobre Claude Code e o futuro das ferramentas de IA.",
    youtubeLink: "https://www.youtube.com/watch?v=h9oDCEIcSVU",
    spotifyLink: "https://open.spotify.com/episode/0ex4SB8kINyAvgLebmZpAK",
  },
  {
    id: 103,
    title: "Você tem Product Sense?",
    date: "2026-01-28",
    description: "Discussão sobre Product Sense e as ferramentas da semana.",
    youtubeLink: "https://www.youtube.com/watch?v=dt3vQX5isqY",
    spotifyLink: "https://open.spotify.com/episode/3ISQhy14KTgTyIWURKarW5",
  },
];
